이름 중복 체크 API 개발
Dog-Han-Developer/doggu pull request #11
Opened 2022-07-12 13:33 UTC by LeeA0

## 목적
- 이메일로 전송받은 인증번호가 올바른지 확인한다.

## 작업 상세 내용
- [x] [DOG-42] 회원 Domain 개발
- 지난 커밋에서 이미 domain을 개발했기 때문에, 이번 수정에서는 unique key만 추가해주었습니다.
- [x] [DOG-39] Controller에 이름 중복 체크 API 개발
- 각 url마다 앞에 붙어있던 /를 제거해주고, 공통 url의 뒤에 /를 붙였습니다.
- [x] [DOG-40] Service에 이름 중복 체크 기능 개발
- [x] [DOG-45] 이미 존재하는 이름인지 체크하는 Repository 개발
- [x] [DOG-69] 사용자 이름 중복 체크 Controller 테스트 코드 작성
- [x] [DOG-70] 사용자 이름 중복 체크 Service 테스트 코드 작성
- [x] [DOG-77] 사용자 이름 중복 체크 DTO 테스트 코드 작성

2022-07-19 14:12 UTC, callipenguin requested changes
항상 좋은 코드 감사합니다!

2022-07-19 14:12 UTC, callipenguin commented on back/src/main/java/com/doghandeveloper/doggu/Account/controller/AccountController.java
> +    @PostMapping("email")
오! 저는 오히려 모든 URI앞에 슬래쉬가 있으면 통일성이 커진다고 생각했습니다 ㅎㅎ
혹시 제가 컨벤션을 잊고 있었다면 죄송합니다 ㅠㅠ

2022-07-19 14:12 UTC, callipenguin commented on back/src/test/java/com/doghandeveloper/doggu/Account/controller/AccountControllerTest.java
> +        String username = "doggu_love";
🎉

2022-07-19 14:13 UTC, LeeA0 commented on back/src/main/java/com/doghandeveloper/doggu/Account/controller/AccountController.java
> +    @PostMapping("email")
아! 딱히 컨벤션으로 지정하진 않았던 것 같습니다. 다만, 공통 URL에 /를 넣으면 앞으로 넣을 필요가 없어 더 깔끔해서 수정했습니다.

2022-07-19 14:14 UTC, callipenguin commented on back/src/main/java/com/doghandeveloper/doggu/Account/controller/AccountController.java
> +    @PostMapping("email")
확실히 중복되는 /를 줄이는 효과는 있는 같네요! 맞춰가겠습니다 :)

2022-08-12 14:24 UTC, leesuuuuumm reviewed
고생 많으셨습니다. :) 코드 참고해서 Testcode 작성해보겠습니다 ㅎㅎ

2022-08-12 14:24 UTC, leesuuuuumm commented on back/src/main/java/com/doghandeveloper/doggu/Account/controller/AccountController.java
>          @ApiResponse(responseCode = "200", description = "인증번호 확인 성공"),
혹시 성공시에는 @content schema를 사용안하는 이유가 있을까요? :)

2022-08-16 14:03 UTC, LeeA0 commented on back/src/main/java/com/doghandeveloper/doggu/Account/controller/AccountController.java
>          @ApiResponse(responseCode = "200", description = "인증번호 확인 성공"),
성공시에는 별도로 반환되는 entity가 없기 때문입니다 :)
다른 질문이 없으시다면 approve 부탁드려요~~

2022-08-16 14:12 UTC, callipenguin commented
행동력 존경스럽습니다...

2022-08-16 14:13 UTC, callipenguin approved these changes
항상 좋은 본보기가 되어주셔서 감사합니다...

2022-08-16 14:28 UTC, merged